# Generated by Django 4.2.7 on 2023-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='mod_file',
            field=models.FileField(default=1, upload_to='mods/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod',
            name='modpacks',
            field=models.ManyToManyField(blank=True, null=True, to='mods.modpack'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='mod_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ModModpack',
        ),
    ]
