# Generated by Django 4.2.7 on 2023-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher_download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='name',
        ),
        migrations.AlterField(
            model_name='launcher',
            name='os',
            field=models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('MAC', 'Mac')], max_length=7),
        ),
    ]
