# Generated by Django 4.2.7 on 2023-11-26 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('icon', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(default=None)),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('java_versions', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='UserServer',
            fields=[
                ('user_storage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
                ('date_last_joined', models.DateTimeField()),
                ('privilege', models.CharField(max_length=40)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
