# Generated by Django 4.2.7 on 2023-11-26 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mod_version', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('is_server', models.BooleanField()),
                ('slug', models.SlugField()),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gameversion')),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('modpack_version', models.CharField(max_length=100)),
                ('is_server', models.BooleanField(default=False)),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gameversion')),
            ],
        ),
        migrations.CreateModel(
            name='ModpackMod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('modpack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.modpack')),
            ],
        ),
        migrations.AddField(
            model_name='modpack',
            name='mods',
            field=models.ManyToManyField(through='mods.ModpackMod', to='mods.mod'),
        ),
    ]
