# Generated by Django 4.2.7 on 2023-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('os', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('MAC', 'Mac')], max_length=7)),
                ('file', models.FileField(upload_to='launchers/')),
            ],
        ),
    ]
