# Generated by Django 4.2.6 on 2023-11-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='modpack_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_modpack_id', to='mods.modpack'),
        ),
        migrations.AlterField(
            model_name='server',
            name='modpack_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_modpack_version', to='mods.modpack'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_img',
            field=models.ImageField(default=None, upload_to='', verbose_name=''),
        ),
    ]
