# Generated by Django 4.2.6 on 2023-11-02 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=40)),
                ('server_img', models.ImageField(default=None, upload_to='', verbose_name='')),
                ('server_description', models.TextField(default=None)),
                ('server_ip', models.CharField(max_length=30)),
                ('java_versions', models.IntegerField()),
                ('minecraft_version', models.CharField(max_length=25)),
                ('loader_core', models.CharField(max_length=50)),
                ('minimal_loader_version', models.CharField(max_length=25)),
                ('server_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('server_slug', models.SlugField()),
                ('modpack_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_modpack_id', to='mod.modpack')),
                ('modpack_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_modpack_version', to='mod.modpack')),
            ],
        ),
        migrations.CreateModel(
            name='UserServer',
            fields=[
                ('user_storage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
                ('date_last_joined', models.DateTimeField()),
                ('privilege', models.CharField(max_length=40)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
