# Generated by Django 4.2.7 on 2023-11-11 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('mod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mod_name', models.CharField(max_length=30)),
                ('mod_versions', models.CharField(max_length=30)),
                ('mod_link', models.CharField(max_length=50)),
                ('mod_descriptions', models.TextField(default=None)),
                ('minecraft_versions', models.CharField(max_length=30)),
                ('loader_core', models.CharField(max_length=50)),
                ('minimal_loader_version', models.CharField(max_length=25)),
                ('is_server', models.BooleanField(default=False)),
                ('mod_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modpack',
            fields=[
                ('modpack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modpack_name', models.CharField(max_length=30)),
                ('mod_count', models.IntegerField(default=0)),
                ('modpack_version', models.CharField(max_length=25)),
                ('minecraft_version', models.CharField(max_length=25)),
                ('loader_core', models.CharField(max_length=50)),
                ('minimal_loader_version', models.CharField(max_length=25)),
                ('is_server', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModModpack',
            fields=[
                ('mod_modpack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minecraft_versions', models.CharField(max_length=25)),
                ('loader_core', models.CharField(max_length=25)),
                ('minimal_loader_versions', models.CharField(max_length=40)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.mod')),
                ('modpack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.modpack')),
            ],
        ),
    ]
